name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: make install

      - name: Run Linter
        run: make lint

      - name: Format Code
        run: make format

      - name: Run Tests
        run: make test

      - name: Lint Dockerfile (if applicable)
        run: make container-lint || echo "Skipping Dockerfile lint"

  deploy:
    needs: build-and-test  # Run deployment only if CI succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: make install

      - name: Deploy Application (Example: Docker & AWS)
        run: |
          echo "Starting Deployment..."
          make deploy  # Replace this with actual deployment commands

      - name: Notify Success
        run: echo "🚀 Deployment Successful!"
