name: CI/CD Pipeline for AI Model

on:
  push:
    branches:
      - main  # ✅ Run CI/CD on every push to 'main'
  pull_request:
    branches:
      - main  # ✅ Run CI/CD on every PR

jobs:
  # ✅ Continuous Integration: Lint & Test
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Linting (Check Code Style)
        run: |
          pip install flake8
          flake8 --max-line-length=88 train.py test.py deploy.py

      - name: Run Unit Tests
        run: |
          pytest test.py  # ✅ Run test cases

  # ✅ Continuous Deployment: Train & Deploy Model
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train AI Model
        run: |
          python train.py  # ✅ Train RL Model

      - name: Upload Model to AWS S3 (Optional)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp models/supply_chain_dqn.zip s3://your-bucket-name/

      - name: Deploy Model
        run: |
          python deploy.py  # ✅ Deploy trained model to cloud API
